name: Check CSV URLs

on:
  push:
    branches:
      - 'main'

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run URL checker
        run: PYTHONPATH=. python src/main.py

      - name: Upload summary as job summary
        if: always()
        run: |
          if [ -f reports/summary.md ]; then
            cat reports/summary.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No summary.md generated." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload summary as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: url-check-summary
          path: reports/summary.md
